name: Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_github_actions:
    strategy:
      matrix:
        arch: [ARM64, X64]
    runs-on:
      - self-hosted
      - Windows
      - ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose -- --nocapture